model:
  name: vgg16
  num_classes: 5
  in_channels: 3
#  init_filters: 4

training:
  batch_size: 32
  epochs: 200
  optimizer:
    name: 'adam'
    weight_decay: 1e-4
    lr: 1e-3
  early_stopping:
    monitor: 'val_loss'  
    patience: 20         
  loss:
    name: 'WeightedCategoricalCrossEntropy' 

data:
  train_csv: 'dataset/configs/split_results/train_split_70.csv'
  val_csv: 'dataset/configs/split_results/val_split_10.csv'
  test_csv: 'dataset/configs/split_results/test_split_20.csv'
  augmentation:
    random_affine:
      p: 0.5
      degrees: 10
      translate: [0.1, 0.1]
      scale: [0.9, 1.1]
    random_flip:
      p: 0.5            